import { drizzle } from "drizzle-orm/node-postgres";
import { Pool } from "pg";
import { businesses, categories, favorites, reviews, searchHistory } from "./schema";

const databaseUrl = process.env.DATABASE_URL;
const hasDatabaseUrl = Boolean(databaseUrl);

const globalForDb = globalThis as typeof globalThis & {
  __arenaNextJsPostgresqlPool?: Pool;
};

export const pool = hasDatabaseUrl
  ? globalForDb.__arenaNextJsPostgresqlPool ??
    new Pool({
      connectionString: databaseUrl,
    })
  : undefined;

if (hasDatabaseUrl && process.env.NODE_ENV !== "production") {
  globalForDb.__arenaNextJsPostgresqlPool = pool;
}

const fallbackCategories = [
  { id: 1, name: "Restaurants", slug: "restaurants", icon: "UtensilsCrossed", color: "#22c55e", description: "Fine dining, casual restaurants, and food courts", businessCount: 2, createdAt: new Date() },
  { id: 2, name: "Cafes", slug: "cafes", icon: "Coffee", color: "#a855f7", description: "Coffee shops, tea houses, and cozy cafes", businessCount: 2, createdAt: new Date() },
  { id: 3, name: "Pharmacies", slug: "pharmacies", icon: "Pill", color: "#ef4444", description: "Medicine shops and pharmacies", businessCount: 2, createdAt: new Date() },
  { id: 4, name: "Grocery", slug: "grocery", icon: "ShoppingCart", color: "#f97316", description: "Super shops and grocery stores", businessCount: 2, createdAt: new Date() },
  { id: 5, name: "Hospitals", slug: "hospitals", icon: "Hospital", color: "#dc2626", description: "Hospitals, clinics, and medical centers", businessCount: 2, createdAt: new Date() },
  { id: 6, name: "Hotels", slug: "hotels", icon: "Hotel", color: "#8b5cf6", description: "Hotels, resorts, and accommodations", businessCount: 2, createdAt: new Date() },
  { id: 7, name: "Shopping", slug: "shopping", icon: "ShoppingBag", color: "#3b82f6", description: "Shopping malls and retail stores", businessCount: 2, createdAt: new Date() },
  { id: 8, name: "Banks & ATMs", slug: "banks-atms", icon: "Landmark", color: "#0ea5e9", description: "Banks, ATMs, and financial services", businessCount: 2, createdAt: new Date() },
  { id: 9, name: "Fuel Stations", slug: "fuel-stations", icon: "Fuel", color: "#eab308", description: "Gas stations and fuel pumps", businessCount: 2, createdAt: new Date() },
  { id: 10, name: "Beauty Salons", slug: "beauty-salons", icon: "Scissors", color: "#ec4899", description: "Salons, spas, and beauty parlors", businessCount: 2, createdAt: new Date() },
  { id: 11, name: "Gyms", slug: "gyms", icon: "Dumbbell", color: "#14b8a6", description: "Fitness centers and gyms", businessCount: 2, createdAt: new Date() },
  { id: 12, name: "Fast Food", slug: "fast-food", icon: "Pizza", color: "#f59e0b", description: "Quick bites and fast food chains", businessCount: 2, createdAt: new Date() },
];

const fallbackBusinesses = [
  { id: 1, name: "The Royal Bengal Kitchen", slug: "royal-bengal-kitchen", categoryId: 1, description: "Authentic Bengali cuisine with a modern twist.", address: "42 Gulshan Ave, Dhaka 1212", latitude: 23.7925, longitude: 90.4078, phone: "+880-2-9881234", email: null, website: null, priceRange: 3, rating: 4.8, reviewCount: 342, imageUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800", photos: ["https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800"], tags: ["Bengali", "Biryani", "Hilsa", "Fine Dining"], features: ["Air Conditioned", "Family Friendly", "Parking", "WiFi"], openingHours: { mon: "11:00-23:00" }, isOpen: true, isPremium: true, isVerified: true, hasDelivery: true, hasWifi: true, hasParking: true, isAirConditioned: true, isFamilyFriendly: true, isWheelchairAccessible: true, hasHalalFood: true, avgBudget: 1200, waitingTime: 15, seatsAvailable: 24, createdAt: new Date(), updatedAt: new Date() },
  { id: 2, name: "Saffron Spice House", slug: "saffron-spice-house", categoryId: 1, description: "Contemporary Indian and Mughlai favorites served in a stylish setting.", address: "18 Dhanmondi 15, Dhaka 1209", latitude: 23.7523, longitude: 90.3771, phone: "+880-1744556677", email: null, website: null, priceRange: 2, rating: 4.5, reviewCount: 214, imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800", photos: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800"], tags: ["Indian", "Mughlai", "Casual", "Halal"], features: ["Delivery", "WiFi", "Parking"], openingHours: { mon: "10:00-22:00" }, isOpen: true, isPremium: false, isVerified: true, hasDelivery: true, hasWifi: true, hasParking: false, isAirConditioned: true, isFamilyFriendly: true, isWheelchairAccessible: false, hasHalalFood: true, avgBudget: 900, waitingTime: 10, seatsAvailable: 36, createdAt: new Date(), updatedAt: new Date() },
  { id: 3, name: "Artisan Coffee House", slug: "artisan-coffee-house", categoryId: 2, description: "Specialty coffee brewed to perfection.", address: "22 Uttara Sector 7, Dhaka 1230", latitude: 23.8759, longitude: 90.3795, phone: "+880-1555667788", email: null, website: null, priceRange: 2, rating: 4.7, reviewCount: 189, imageUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800", photos: ["https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800"], tags: ["Coffee", "Study", "WiFi", "Quiet"], features: ["WiFi", "Air Conditioned", "Power Outlets"], openingHours: { mon: "07:00-22:00" }, isOpen: true, isPremium: true, isVerified: true, hasDelivery: false, hasWifi: true, hasParking: true, isAirConditioned: true, isFamilyFriendly: true, isWheelchairAccessible: true, hasHalalFood: true, avgBudget: 500, waitingTime: 5, seatsAvailable: 30, createdAt: new Date(), updatedAt: new Date() },
  { id: 4, name: "Green Leaf Tea Lounge", slug: "green-leaf-tea-lounge", categoryId: 2, description: "A serene tea lounge offering 50+ varieties of tea from around the world.", address: "33 Gulshan 2, Dhaka 1212", latitude: 23.7935, longitude: 90.4141, phone: "+880-1777889900", email: null, website: null, priceRange: 2, rating: 4.4, reviewCount: 123, imageUrl: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800", photos: ["https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800"], tags: ["Tea", "Relaxation", "Quiet", "Aesthetic"], features: ["WiFi", "Air Conditioned", "Garden Seating"], openingHours: { mon: "08:00-21:00" }, isOpen: true, isPremium: false, isVerified: true, hasDelivery: true, hasWifi: true, hasParking: false, isAirConditioned: true, isFamilyFriendly: true, isWheelchairAccessible: false, hasHalalFood: true, avgBudget: 400, waitingTime: 8, seatsAvailable: 18, createdAt: new Date(), updatedAt: new Date() },
  { id: 5, name: "LifeCare Pharmacy", slug: "lifecare-pharmacy", categoryId: 3, description: "24/7 pharmacy with a wide range of medicines and health essentials.", address: "10 Mohakhali, Dhaka 1212", latitude: 23.778, longitude: 90.404, phone: "+880-2-9988776", email: null, website: null, priceRange: 2, rating: 4.6, reviewCount: 89, imageUrl: "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=800", photos: ["https://images.unsplash.com/photo-1576602976047-174e57a47881?w=800"], tags: ["24/7", "Medicine", "Emergency", "Health"], features: ["Home Delivery", "Pharmacist Consultation", "Baby Products"], openingHours: { mon: "00:00-23:59" }, isOpen: true, isPremium: false, isVerified: true, hasDelivery: true, hasWifi: false, hasParking: true, isAirConditioned: true, isFamilyFriendly: true, isWheelchairAccessible: true, hasHalalFood: false, avgBudget: 500, waitingTime: 3, seatsAvailable: 0, createdAt: new Date(), updatedAt: new Date() },
  { id: 6, name: "MediPlus Outlet", slug: "mediplus-outlet", categoryId: 3, description: "Fast and reliable medicine delivery for daily essentials.", address: "55 Banani, Dhaka 1213", latitude: 23.7936, longitude: 90.4057, phone: "+880-1911223344", email: null, website: null, priceRange: 1, rating: 4.3, reviewCount: 67, imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800", photos: ["https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800"], tags: ["Medicine", "Fast Service", "Convenient"], features: ["24/7 Open", "Pickup", "Home Delivery"], openingHours: { mon: "08:00-22:00" }, isOpen: true, isPremium: false, isVerified: true, hasDelivery: true, hasWifi: false, hasParking: true, isAirConditioned: true, isFamilyFriendly: true, isWheelchairAccessible: false, hasHalalFood: false, avgBudget: 300, waitingTime: 2, seatsAvailable: 10, createdAt: new Date(), updatedAt: new Date() },
  { id: 7, name: "FreshMart Supershop", slug: "freshmart-supershop", categoryId: 4, description: "Your one-stop shop for fresh produce, groceries, and home essentials.", address: "88 Bashundhara R/A, Dhaka 1229", latitude: 23.8126, longitude: 90.4254, phone: "+880-2-8811234", email: null, website: null, priceRange: 2, rating: 4.4, reviewCount: 267, imageUrl: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800", photos: ["https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800"], tags: ["Grocery", "Fresh Produce", "Organic", "Import"], features: ["Air Conditioned", "Parking", "Home Delivery"], openingHours: { mon: "09:00-22:00" }, isOpen: true, isPremium: true, isVerified: true, hasDelivery: true, hasWifi: false, hasParking: true, isAirConditioned: true, isFamilyFriendly: true, isWheelchairAccessible: true, hasHalalFood: true, avgBudget: 2000, waitingTime: 10, seatsAvailable: 45, createdAt: new Date(), updatedAt: new Date() },
  { id: 8, name: "Daily Basket", slug: "daily-basket", categoryId: 4, description: "Everyday groceries delivered quickly with a personal touch.", address: "12 Mirpur Road, Dhaka 1205", latitude: 23.7592, longitude: 90.3818, phone: "+880-1811223344", email: null, website: null, priceRange: 1, rating: 4.2, reviewCount: 146, imageUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800", photos: ["https://images.unsplash.com/photo-1542838132-92c53300491e?w=800"], tags: ["Groceries", "Budget", "Quick Delivery"], features: ["Delivery", "Pickup", "Budget Friendly"], openingHours: { mon: "08:00-21:00" }, isOpen: true, isPremium: false, isVerified: true, hasDelivery: true, hasWifi: false, hasParking: false, isAirConditioned: false, isFamilyFriendly: true, isWheelchairAccessible: false, hasHalalFood: true, avgBudget: 800, waitingTime: 6, seatsAvailable: 20, createdAt: new Date(), updatedAt: new Date() },
  { id: 9, name: "CityCare Hospital", slug: "citycare-hospital", categoryId: 5, description: "Modern healthcare center with emergency and specialist services.", address: "4 Baridhara, Dhaka 1212", latitude: 23.8078, longitude: 90.4202, phone: "+880-2-8833444", email: null, website: null, priceRange: 3, rating: 4.8, reviewCount: 311, imageUrl: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800", photos: ["https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800"], tags: ["Hospital", "Emergency", "Specialist"], features: ["24/7", "Emergency", "Parking"], openingHours: { mon: "00:00-23:59" }, isOpen: true, isPremium: true, isVerified: true, hasDelivery: false, hasWifi: true, hasParking: true, isAirConditioned: true, isFamilyFriendly: true, isWheelchairAccessible: true, hasHalalFood: false, avgBudget: 1500, waitingTime: 12, seatsAvailable: 0, createdAt: new Date(), updatedAt: new Date() },
  { id: 10, name: "Family Medical Center", slug: "family-medical-center", categoryId: 5, description: "Trusted family clinic with advanced diagnostics and pediatrics.", address: "16 Gulshan 1, Dhaka 1212", latitude: 23.7934, longitude: 90.4091, phone: "+880-1919887766", email: null, website: null, priceRange: 2, rating: 4.6, reviewCount: 182, imageUrl: "https://images.unsplash.com/photo-1584515933487-779824d29309?w=800", photos: ["https://images.unsplash.com/photo-1584515933487-779824d29309?w=800"], tags: ["Clinic", "Pediatrics", "Care"], features: ["Walk-in", "Diagnostics", "Parking"], openingHours: { mon: "08:00-20:00" }, isOpen: true, isPremium: false, isVerified: true, hasDelivery: false, hasWifi: true, hasParking: true, isAirConditioned: true, isFamilyFriendly: true, isWheelchairAccessible: true, hasHalalFood: false, avgBudget: 800, waitingTime: 7, seatsAvailable: 12, createdAt: new Date(), updatedAt: new Date() },
  { id: 11, name: "The Grand Horizon", slug: "the-grand-horizon", categoryId: 6, description: "Luxury hotel with rooftop dining and event facilities.", address: "1 Airport Road, Dhaka 1229", latitude: 23.8516, longitude: 90.4028, phone: "+880-2-8123456", email: null, website: null, priceRange: 4, rating: 4.9, reviewCount: 512, imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800", photos: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800"], tags: ["Hotel", "Luxury", "Travel"], features: ["WiFi", "Parking", "Pool", "Spa"], openingHours: { mon: "00:00-23:59" }, isOpen: true, isPremium: true, isVerified: true, hasDelivery: false, hasWifi: true, hasParking: true, isAirConditioned: true, isFamilyFriendly: true, isWheelchairAccessible: true, hasHalalFood: true, avgBudget: 4500, waitingTime: 4, seatsAvailable: 32, createdAt: new Date(), updatedAt: new Date() },
  { id: 12, name: "Comfort Stay Suites", slug: "comfort-stay-suites", categoryId: 6, description: "Comfortable suites with fast check-in and business amenities.", address: "9 Panthapath, Dhaka 1205", latitude: 23.7517, longitude: 90.3864, phone: "+880-1712345678", email: null, website: null, priceRange: 3, rating: 4.4, reviewCount: 205, imageUrl: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800", photos: ["https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800"], tags: ["Stay", "Business", "Travel"], features: ["WiFi", "Breakfast", "Parking"], openingHours: { mon: "00:00-23:59" }, isOpen: true, isPremium: false, isVerified: true, hasDelivery: false, hasWifi: true, hasParking: true, isAirConditioned: true, isFamilyFriendly: true, isWheelchairAccessible: true, hasHalalFood: true, avgBudget: 2500, waitingTime: 5, seatsAvailable: 18, createdAt: new Date(), updatedAt: new Date() },
  { id: 13, name: "Metro Mall", slug: "metro-mall", categoryId: 7, description: "A lively retail destination for fashion, gadgets, and lifestyle shopping.", address: "12 New Market, Dhaka 1205", latitude: 23.7302, longitude: 90.3924, phone: "+880-2-9665432", email: null, website: null, priceRange: 3, rating: 4.7, reviewCount: 389, imageUrl: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=800", photos: ["https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=800"], tags: ["Shopping", "Mall", "Fashion"], features: ["Parking", "WiFi", "Elevators"], openingHours: { mon: "10:00-21:00" }, isOpen: true, isPremium: true, isVerified: true, hasDelivery: false, hasWifi: true, hasParking: true, isAirConditioned: true, isFamilyFriendly: true, isWheelchairAccessible: true, hasHalalFood: false, avgBudget: 1800, waitingTime: 8, seatsAvailable: 100, createdAt: new Date(), updatedAt: new Date() },
  { id: 14, name: "Brand Hub", slug: "brand-hub", categoryId: 7, description: "Boutique retail space with curated local and international labels.", address: "7 Gulshan Circle 2, Dhaka 1212", latitude: 23.7898, longitude: 90.4174, phone: "+880-1711221188", email: null, website: null, priceRange: 2, rating: 4.3, reviewCount: 154, imageUrl: "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?w=800", photos: ["https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?w=800"], tags: ["Store", "Retail", "Lifestyle"], features: ["Parking", "WiFi", "Customer Service"], openingHours: { mon: "11:00-20:00" }, isOpen: true, isPremium: false, isVerified: true, hasDelivery: false, hasWifi: true, hasParking: true, isAirConditioned: true, isFamilyFriendly: true, isWheelchairAccessible: true, hasHalalFood: false, avgBudget: 1200, waitingTime: 6, seatsAvailable: 50, createdAt: new Date(), updatedAt: new Date() },
  { id: 15, name: "Prime Bank ATM", slug: "prime-bank-atm", categoryId: 8, description: "Secure ATM service with card and cash support around the clock.", address: "3 Bashundhara Link Road, Dhaka 1229", latitude: 23.8157, longitude: 90.428, phone: "+880-2-9110000", email: null, website: null, priceRange: 1, rating: 4.1, reviewCount: 76, imageUrl: "https://images.unsplash.com/photo-1556740749-887f6717d7e4?w=800", photos: ["https://images.unsplash.com/photo-1556740749-887f6717d7e4?w=800"], tags: ["ATM", "Banking", "Cash"], features: ["24/7", "Secure", "Card Support"], openingHours: { mon: "00:00-23:59" }, isOpen: true, isPremium: false, isVerified: true, hasDelivery: false, hasWifi: false, hasParking: true, isAirConditioned: true, isFamilyFriendly: false, isWheelchairAccessible: true, hasHalalFood: false, avgBudget: 100, waitingTime: 1, seatsAvailable: 5, createdAt: new Date(), updatedAt: new Date() },
  { id: 16, name: "North Star Bank", slug: "north-star-bank", categoryId: 8, description: "Full-service bank branch for accounts, transfers, and loans.", address: "21 Dhanmondi 10, Dhaka 1209", latitude: 23.7482, longitude: 90.3777, phone: "+880-2-9876543", email: null, website: null, priceRange: 2, rating: 4.5, reviewCount: 132, imageUrl: "https://images.unsplash.com/photo-1613909207039-6b173b755cc1?w=800", photos: ["https://images.unsplash.com/photo-1613909207039-6b173b755cc1?w=800"], tags: ["Bank", "Finance", "Loans"], features: ["Account Service", "ATM", "Secure"], openingHours: { mon: "09:00-15:00" }, isOpen: true, isPremium: false, isVerified: true, hasDelivery: false, hasWifi: true, hasParking: true, isAirConditioned: true, isFamilyFriendly: false, isWheelchairAccessible: true, hasHalalFood: false, avgBudget: 200, waitingTime: 3, seatsAvailable: 12, createdAt: new Date(), updatedAt: new Date() },
  { id: 17, name: "Eco Fuel Station", slug: "eco-fuel-station", categoryId: 9, description: "Clean fuel station with quick service and convenience store.", address: "88 Airport Road, Dhaka 1229", latitude: 23.8508, longitude: 90.4012, phone: "+880-1712334455", email: null, website: null, priceRange: 1, rating: 4.2, reviewCount: 98, imageUrl: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=800", photos: ["https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=800"], tags: ["Fuel", "Gas", "Quick Stop"], features: ["24/7", "Convenience", "Car Wash"], openingHours: { mon: "00:00-23:59" }, isOpen: true, isPremium: false, isVerified: true, hasDelivery: false, hasWifi: false, hasParking: true, isAirConditioned: true, isFamilyFriendly: true, isWheelchairAccessible: true, hasHalalFood: false, avgBudget: 120, waitingTime: 2, seatsAvailable: 15, createdAt: new Date(), updatedAt: new Date() },
  { id: 18, name: "Metro Fuel Point", slug: "metro-fuel-point", categoryId: 9, description: "High-speed fuel service with lounge and restrooms.", address: "5 Kuril Bishwa Road, Dhaka 1229", latitude: 23.825, longitude: 90.424, phone: "+880-1910001122", email: null, website: null, priceRange: 1, rating: 4.4, reviewCount: 112, imageUrl: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800", photos: ["https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800"], tags: ["Gas", "Petrol", "Travel"], features: ["Restroom", "Cafe", "Parking"], openingHours: { mon: "00:00-23:59" }, isOpen: true, isPremium: false, isVerified: true, hasDelivery: false, hasWifi: false, hasParking: true, isAirConditioned: true, isFamilyFriendly: true, isWheelchairAccessible: true, hasHalalFood: false, avgBudget: 140, waitingTime: 3, seatsAvailable: 10, createdAt: new Date(), updatedAt: new Date() },
  { id: 19, name: "Luxe Salon Studio", slug: "luxe-salon-studio", categoryId: 10, description: "Stylish beauty services for hair, nails, and skincare.", address: "11 Banani, Dhaka 1213", latitude: 23.7926, longitude: 90.408, phone: "+880-1733445566", email: null, website: null, priceRange: 2, rating: 4.7, reviewCount: 165, imageUrl: "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=800", photos: ["https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=800"], tags: ["Salon", "Beauty", "Skincare"], features: ["Hair", "Nails", "Spa"], openingHours: { mon: "10:00-20:00" }, isOpen: true, isPremium: true, isVerified: true, hasDelivery: false, hasWifi: true, hasParking: true, isAirConditioned: true, isFamilyFriendly: true, isWheelchairAccessible: true, hasHalalFood: false, avgBudget: 900, waitingTime: 4, seatsAvailable: 8, createdAt: new Date(), updatedAt: new Date() },
  { id: 20, name: "Glow Beauty Bar", slug: "glow-beauty-bar", categoryId: 10, description: "Relaxing beauty treatments and premium styling with expert therapists.", address: "6 Uttara Sector 4, Dhaka 1230", latitude: 23.8764, longitude: 90.3798, phone: "+880-1819988777", email: null, website: null, priceRange: 2, rating: 4.5, reviewCount: 134, imageUrl: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800", photos: ["https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800"], tags: ["Spa", "Beauty", "Relaxation"], features: ["Facials", "Massage", "Haircut"], openingHours: { mon: "09:00-19:00" }, isOpen: true, isPremium: false, isVerified: true, hasDelivery: false, hasWifi: true, hasParking: true, isAirConditioned: true, isFamilyFriendly: true, isWheelchairAccessible: true, hasHalalFood: false, avgBudget: 700, waitingTime: 5, seatsAvailable: 12, createdAt: new Date(), updatedAt: new Date() },
  { id: 21, name: "PowerFit Gym", slug: "powerfit-gym", categoryId: 11, description: "High-performance gym with modern equipment and coaching.", address: "14 Mirpur DOHS, Dhaka 1216", latitude: 23.8122, longitude: 90.3679, phone: "+880-1788990011", email: null, website: null, priceRange: 2, rating: 4.7, reviewCount: 289, imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800", photos: ["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800"], tags: ["Gym", "Fitness", "Workout"], features: ["Equipment", "Trainer", "Locker"], openingHours: { mon: "06:00-22:00" }, isOpen: true, isPremium: true, isVerified: true, hasDelivery: false, hasWifi: true, hasParking: true, isAirConditioned: true, isFamilyFriendly: false, isWheelchairAccessible: true, hasHalalFood: false, avgBudget: 1100, waitingTime: 4, seatsAvailable: 35, createdAt: new Date(), updatedAt: new Date() },
  { id: 22, name: "Pulse Fitness Club", slug: "pulse-fitness-club", categoryId: 11, description: "A welcoming fitness club with yoga, boxing, and strength classes.", address: "8 Gulshan 3, Dhaka 1212", latitude: 23.7929, longitude: 90.4136, phone: "+880-1912345678", email: null, website: null, priceRange: 2, rating: 4.5, reviewCount: 201, imageUrl: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800", photos: ["https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800"], tags: ["Fitness", "Yoga", "Training"], features: ["Classes", "Swimming", "Sauna"], openingHours: { mon: "05:00-23:00" }, isOpen: true, isPremium: false, isVerified: true, hasDelivery: false, hasWifi: true, hasParking: true, isAirConditioned: true, isFamilyFriendly: false, isWheelchairAccessible: true, hasHalalFood: false, avgBudget: 900, waitingTime: 5, seatsAvailable: 22, createdAt: new Date(), updatedAt: new Date() },
  { id: 23, name: "Crunch Burger Spot", slug: "crunch-burger-spot", categoryId: 12, description: "Fast and tasty burgers, fries, and shakes for any craving.", address: "5 Dhanmondi 8, Dhaka 1209", latitude: 23.7467, longitude: 90.3766, phone: "+880-1711112233", email: null, website: null, priceRange: 1, rating: 4.4, reviewCount: 176, imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800", photos: ["https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800"], tags: ["Fast Food", "Burger", "Quick Bite"], features: ["Delivery", "Takeaway", "Late Night"], openingHours: { mon: "10:00-00:00" }, isOpen: true, isPremium: false, isVerified: true, hasDelivery: true, hasWifi: false, hasParking: false, isAirConditioned: false, isFamilyFriendly: true, isWheelchairAccessible: false, hasHalalFood: true, avgBudget: 400, waitingTime: 4, seatsAvailable: 14, createdAt: new Date(), updatedAt: new Date() },
  { id: 24, name: "Pizza Corner", slug: "pizza-corner", categoryId: 12, description: "Fresh pizzas and sides with quick delivery and cozy seating.", address: "19 Banani, Dhaka 1213", latitude: 23.7933, longitude: 90.4089, phone: "+880-1888877665", email: null, website: null, priceRange: 1, rating: 4.3, reviewCount: 143, imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800", photos: ["https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800"], tags: ["Pizza", "Fast Food", "Delivery"], features: ["Delivery", "Takeaway", "WiFi"], openingHours: { mon: "11:00-23:00" }, isOpen: true, isPremium: false, isVerified: true, hasDelivery: true, hasWifi: true, hasParking: false, isAirConditioned: true, isFamilyFriendly: true, isWheelchairAccessible: true, hasHalalFood: true, avgBudget: 600, waitingTime: 6, seatsAvailable: 20, createdAt: new Date(), updatedAt: new Date() },
];

const fallbackReviews = [
  {
    id: 1,
    businessId: 1,
    userName: "Amina",
    rating: 5,
    comment: "Excellent food and great ambiance.",
    createdAt: new Date(),
  },
];

const fallbackRows = new Map<unknown, unknown[]>([
  [categories, fallbackCategories],
  [businesses, fallbackBusinesses],
  [reviews, fallbackReviews],
  [favorites, []],
  [searchHistory, []],
]);

function createFallbackQueryResult(rows: unknown[]) {
  const query = Promise.resolve(rows) as Promise<unknown[]> & {
    where: (condition: unknown) => Promise<unknown[]>;
  };

  query.where = () => query;
  return query;
}

function createFallbackDb() {
  return {
    select() {
      return {
        from(table: unknown) {
          return createFallbackQueryResult(fallbackRows.get(table) ?? []);
        },
      };
    },
  };
}

const fallbackDb = createFallbackDb();

if (!hasDatabaseUrl) {
  console.warn("DATABASE_URL is not configured. Running with demo data in development mode.");
}

export const db = hasDatabaseUrl ? drizzle(pool as Pool) : (fallbackDb as any);
export const isDatabaseConfigured = hasDatabaseUrl;
