import { db } from "./index";
import { categories, businesses, reviews } from "./schema";

const categoryData = [
  { name: "Restaurants", slug: "restaurants", icon: "UtensilsCrossed", color: "#22c55e", description: "Fine dining, casual restaurants, and food courts", businessCount: 48 },
  { name: "Cafes", slug: "cafes", icon: "Coffee", color: "#a855f7", description: "Coffee shops, tea houses, and cozy cafes", businessCount: 32 },
  { name: "Pharmacies", slug: "pharmacies", icon: "Pill", color: "#ef4444", description: "Medicine shops and pharmacies", businessCount: 24 },
  { name: "Grocery", slug: "grocery", icon: "ShoppingCart", color: "#f97316", description: "Super shops and grocery stores", businessCount: 36 },
  { name: "Hospitals", slug: "hospitals", icon: "Hospital", color: "#dc2626", description: "Hospitals, clinics, and medical centers", businessCount: 18 },
  { name: "Hotels", slug: "hotels", icon: "Hotel", color: "#8b5cf6", description: "Hotels, resorts, and accommodations", businessCount: 22 },
  { name: "Shopping", slug: "shopping", icon: "ShoppingBag", color: "#3b82f6", description: "Shopping malls and retail stores", businessCount: 28 },
  { name: "Banks & ATMs", slug: "banks-atms", icon: "Landmark", color: "#0ea5e9", description: "Banks, ATMs, and financial services", businessCount: 42 },
  { name: "Fuel Stations", slug: "fuel-stations", icon: "Fuel", color: "#eab308", description: "Gas stations and fuel pumps", businessCount: 15 },
  { name: "Beauty Salons", slug: "beauty-salons", icon: "Scissors", color: "#ec4899", description: "Salons, spas, and beauty parlors", businessCount: 20 },
  { name: "Gyms", slug: "gyms", icon: "Dumbbell", color: "#14b8a6", description: "Fitness centers and gyms", businessCount: 16 },
  { name: "Fast Food", slug: "fast-food", icon: "Pizza", color: "#f59e0b", description: "Quick bites and fast food chains", businessCount: 38 },
];

const businessData = [
  // Restaurants
  {
    name: "The Royal Bengal Kitchen",
    slug: "royal-bengal-kitchen",
    categoryId: 1,
    description: "Authentic Bengali cuisine with a modern twist. Known for our signature biryani and hilsa preparations.",
    address: "42 Gulshan Ave, Dhaka 1212",
    latitude: 23.7925,
    longitude: 90.4078,
    phone: "+880-2-9881234",
    priceRange: 3,
    rating: 4.8,
    reviewCount: 342,
    imageUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
    tags: ["Bengali", "Biryani", "Hilsa", "Fine Dining", "Halal"],
    features: ["Air Conditioned", "Family Friendly", "Parking", "WiFi", "Live Music"],
    isOpen: true,
    isPremium: true,
    isVerified: true,
    hasDelivery: true,
    hasWifi: true,
    hasParking: true,
    isAirConditioned: true,
    isFamilyFriendly: true,
    isWheelchairAccessible: true,
    hasHalalFood: true,
    avgBudget: 1200,
    waitingTime: 15,
    seatsAvailable: 24,
    openingHours: { mon: "11:00-23:00", tue: "11:00-23:00", wed: "11:00-23:00", thu: "11:00-23:00", fri: "11:00-00:00", sat: "11:00-00:00", sun: "12:00-22:00" },
  },
  {
    name: "Spice Garden",
    slug: "spice-garden",
    categoryId: 1,
    description: "Multi-cuisine restaurant specializing in North Indian and Mughlai dishes. Perfect for family gatherings.",
    address: "15 Dhanmondi 27, Dhaka 1209",
    latitude: 23.7461,
    longitude: 90.3742,
    phone: "+880-2-9123456",
    priceRange: 2,
    rating: 4.5,
    reviewCount: 218,
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800",
    tags: ["Indian", "Mughlai", "Multi-cuisine", "Halal", "Affordable"],
    features: ["Air Conditioned", "Family Friendly", "Delivery", "WiFi"],
    isOpen: true,
    isPremium: false,
    isVerified: true,
    hasDelivery: true,
    hasWifi: true,
    hasParking: false,
    isAirConditioned: true,
    isFamilyFriendly: true,
    isWheelchairAccessible: false,
    hasHalalFood: true,
    avgBudget: 800,
    waitingTime: 10,
    seatsAvailable: 40,
    openingHours: { mon: "10:00-22:00", tue: "10:00-22:00", wed: "10:00-22:00", thu: "10:00-22:00", fri: "10:00-23:00", sat: "10:00-23:00", sun: "11:00-21:00" },
  },
  {
    name: "Sushi Zen",
    slug: "sushi-zen",
    categoryId: 1,
    description: "Premium Japanese restaurant serving authentic sushi, ramen, and teppanyaki. Fresh ingredients imported weekly.",
    address: "78 Banani DOHS, Dhaka 1206",
    latitude: 23.7937,
    longitude: 90.4033,
    phone: "+880-2-8765432",
    priceRange: 4,
    rating: 4.9,
    reviewCount: 156,
    imageUrl: "https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=800",
    tags: ["Japanese", "Sushi", "Ramen", "Premium", "Date Night"],
    features: ["Air Conditioned", "Parking", "WiFi", "Private Dining", "Reservation"],
    isOpen: true,
    isPremium: true,
    isVerified: true,
    hasDelivery: false,
    hasWifi: true,
    hasParking: true,
    isAirConditioned: true,
    isFamilyFriendly: true,
    isWheelchairAccessible: true,
    hasHalalFood: false,
    avgBudget: 3500,
    waitingTime: 20,
    seatsAvailable: 8,
    openingHours: { mon: "12:00-22:00", tue: "12:00-22:00", wed: "12:00-22:00", thu: "12:00-22:00", fri: "12:00-23:00", sat: "12:00-23:00", sun: "12:00-21:00" },
  },
  {
    name: "Street Bites Dhaka",
    slug: "street-bites-dhaka",
    categoryId: 1,
    description: "Best street food flavors in a comfortable setting. From fuchka to jhalmuri, experience authentic street cuisine.",
    address: "5 Mirpur Road, Dhaka 1205",
    latitude: 23.7586,
    longitude: 90.3829,
    phone: "+880-1711223344",
    priceRange: 1,
    rating: 4.3,
    reviewCount: 567,
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800",
    tags: ["Street Food", "Budget", "Quick Bites", "Halal", "Local"],
    features: ["Quick Service", "Delivery", "Takeaway"],
    isOpen: true,
    isPremium: false,
    isVerified: true,
    hasDelivery: true,
    hasWifi: false,
    hasParking: false,
    isAirConditioned: false,
    isFamilyFriendly: true,
    isWheelchairAccessible: false,
    hasHalalFood: true,
    avgBudget: 300,
    waitingTime: 5,
    seatsAvailable: 60,
    openingHours: { mon: "09:00-23:00", tue: "09:00-23:00", wed: "09:00-23:00", thu: "09:00-23:00", fri: "09:00-00:00", sat: "09:00-00:00", sun: "10:00-22:00" },
  },
  // Cafes
  {
    name: "Artisan Coffee House",
    slug: "artisan-coffee-house",
    categoryId: 2,
    description: "Specialty coffee brewed to perfection. Quiet atmosphere perfect for studying or remote work.",
    address: "22 Uttara Sector 7, Dhaka 1230",
    latitude: 23.8759,
    longitude: 90.3795,
    phone: "+880-1555667788",
    priceRange: 2,
    rating: 4.7,
    reviewCount: 189,
    imageUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800",
    tags: ["Coffee", "Study", "WiFi", "Quiet", "Specialty"],
    features: ["WiFi", "Power Outlets", "Air Conditioned", "Quiet Zone", "Books"],
    isOpen: true,
    isPremium: true,
    isVerified: true,
    hasDelivery: false,
    hasWifi: true,
    hasParking: true,
    isAirConditioned: true,
    isFamilyFriendly: true,
    isWheelchairAccessible: true,
    hasHalalFood: true,
    avgBudget: 500,
    waitingTime: 5,
    seatsAvailable: 30,
    openingHours: { mon: "07:00-22:00", tue: "07:00-22:00", wed: "07:00-22:00", thu: "07:00-22:00", fri: "07:00-23:00", sat: "08:00-23:00", sun: "08:00-21:00" },
  },
  {
    name: "Green Leaf Tea Lounge",
    slug: "green-leaf-tea-lounge",
    categoryId: 2,
    description: "A serene tea lounge offering 50+ varieties of tea from around the world. Perfect for relaxation.",
    address: "33 Gulshan 2, Dhaka 1212",
    latitude: 23.7935,
    longitude: 90.4141,
    phone: "+880-1777889900",
    priceRange: 2,
    rating: 4.4,
    reviewCount: 123,
    imageUrl: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800",
    tags: ["Tea", "Relaxation", "Quiet", "Aesthetic", "Pastries"],
    features: ["WiFi", "Air Conditioned", "Garden Seating", "Live Music Weekends"],
    isOpen: true,
    isPremium: false,
    isVerified: true,
    hasDelivery: true,
    hasWifi: true,
    hasParking: false,
    isAirConditioned: true,
    isFamilyFriendly: true,
    isWheelchairAccessible: false,
    hasHalalFood: true,
    avgBudget: 400,
    waitingTime: 8,
    seatsAvailable: 18,
    openingHours: { mon: "08:00-21:00", tue: "08:00-21:00", wed: "08:00-21:00", thu: "08:00-21:00", fri: "08:00-22:00", sat: "09:00-22:00", sun: "09:00-20:00" },
  },
  // Pharmacies
  {
    name: "LifeCare Pharmacy",
    slug: "lifecare-pharmacy",
    categoryId: 3,
    description: "24/7 pharmacy with a wide range of medicines, baby products, and health essentials. Certified pharmacist on duty.",
    address: "10 Mohakhali, Dhaka 1212",
    latitude: 23.7780,
    longitude: 90.4040,
    phone: "+880-2-9988776",
    priceRange: 2,
    rating: 4.6,
    reviewCount: 89,
    imageUrl: "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=800",
    tags: ["24/7", "Medicine", "Baby Products", "Health", "Emergency"],
    features: ["24/7 Open", "Home Delivery", "Pharmacist Consultation", "Baby Products"],
    isOpen: true,
    isPremium: false,
    isVerified: true,
    hasDelivery: true,
    hasWifi: false,
    hasParking: true,
    isAirConditioned: true,
    isFamilyFriendly: true,
    isWheelchairAccessible: true,
    hasHalalFood: false,
    avgBudget: 500,
    waitingTime: 3,
    seatsAvailable: 0,
    openingHours: { mon: "00:00-23:59", tue: "00:00-23:59", wed: "00:00-23:59", thu: "00:00-23:59", fri: "00:00-23:59", sat: "00:00-23:59", sun: "00:00-23:59" },
  },
  // Grocery
  {
    name: "FreshMart Supershop",
    slug: "freshmart-supershop",
    categoryId: 4,
    description: "Your one-stop shop for fresh produce, groceries, baby essentials, and household items. Quality guaranteed.",
    address: "88 Bashundhara R/A, Dhaka 1229",
    latitude: 23.8126,
    longitude: 90.4254,
    phone: "+880-2-8811234",
    priceRange: 2,
    rating: 4.4,
    reviewCount: 267,
    imageUrl: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800",
    tags: ["Grocery", "Fresh Produce", "Baby Products", "Organic", "Import"],
    features: ["Air Conditioned", "Parking", "Home Delivery", "Loyalty Program"],
    isOpen: true,
    isPremium: true,
    isVerified: true,
    hasDelivery: true,
    hasWifi: false,
    hasParking: true,
    isAirConditioned: true,
    isFamilyFriendly: true,
    isWheelchairAccessible: true,
    hasHalalFood: true,
    avgBudget: 2000,
    waitingTime: 10,
    seatsAvailable: 0,
    openingHours: { mon: "08:00-22:00", tue: "08:00-22:00", wed: "08:00-22:00", thu: "08:00-22:00", fri: "08:00-23:00", sat: "08:00-23:00", sun: "09:00-21:00" },
  },
  // Hospitals
  {
    name: "City Medical Center",
    slug: "city-medical-center",
    categoryId: 5,
    description: "Multi-specialty hospital with 24/7 emergency services, ICU, and outpatient care. Board-certified doctors.",
    address: "55 Green Road, Dhaka 1205",
    latitude: 23.7488,
    longitude: 90.3855,
    phone: "+880-2-8811999",
    priceRange: 3,
    rating: 4.5,
    reviewCount: 445,
    imageUrl: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800",
    tags: ["24/7", "Emergency", "ICU", "Multi-specialty", "Ambulance"],
    features: ["24/7 Emergency", "ICU", "Ambulance", "Pharmacy", "Parking", "Wheelchair Accessible"],
    isOpen: true,
    isPremium: true,
    isVerified: true,
    hasDelivery: false,
    hasWifi: true,
    hasParking: true,
    isAirConditioned: true,
    isFamilyFriendly: true,
    isWheelchairAccessible: true,
    hasHalalFood: true,
    avgBudget: 5000,
    waitingTime: 15,
    seatsAvailable: 0,
    openingHours: { mon: "00:00-23:59", tue: "00:00-23:59", wed: "00:00-23:59", thu: "00:00-23:59", fri: "00:00-23:59", sat: "00:00-23:59", sun: "00:00-23:59" },
  },
  // Hotels
  {
    name: "The Grand Dhaka",
    slug: "grand-dhaka",
    categoryId: 6,
    description: "5-star luxury hotel with world-class amenities. Rooftop pool, spa, multiple restaurants, and conference facilities.",
    address: "1 Airport Road, Dhaka 1229",
    latitude: 23.8433,
    longitude: 90.3977,
    phone: "+880-2-8411111",
    priceRange: 4,
    rating: 4.7,
    reviewCount: 312,
    imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
    tags: ["Luxury", "5-Star", "Pool", "Spa", "Conference", "Restaurant"],
    features: ["Pool", "Spa", "Gym", "Restaurant", "Conference Room", "Airport Shuttle", "Valet Parking"],
    isOpen: true,
    isPremium: true,
    isVerified: true,
    hasDelivery: false,
    hasWifi: true,
    hasParking: true,
    isAirConditioned: true,
    isFamilyFriendly: true,
    isWheelchairAccessible: true,
    hasHalalFood: true,
    avgBudget: 15000,
    waitingTime: 0,
    seatsAvailable: 45,
    openingHours: { mon: "00:00-23:59", tue: "00:00-23:59", wed: "00:00-23:59", thu: "00:00-23:59", fri: "00:00-23:59", sat: "00:00-23:59", sun: "00:00-23:59" },
  },
  // Shopping
  {
    name: "Bashundhara City Mall",
    slug: "bashundhara-city-mall",
    categoryId: 7,
    description: "The largest shopping mall in South Asia. 2000+ shops, food court, cinema, and entertainment zone.",
    address: "Panthapath, Dhaka 1205",
    latitude: 23.7509,
    longitude: 90.3875,
    phone: "+880-2-9143000",
    priceRange: 3,
    rating: 4.3,
    reviewCount: 890,
    imageUrl: "https://images.unsplash.com/photo-1519567241046-7f570ef9e0e3?w=800",
    tags: ["Shopping", "Mall", "Cinema", "Food Court", "Entertainment"],
    features: ["Air Conditioned", "Parking", "Food Court", "Cinema", "ATM", "Wheelchair Accessible"],
    isOpen: true,
    isPremium: true,
    isVerified: true,
    hasDelivery: false,
    hasWifi: true,
    hasParking: true,
    isAirConditioned: true,
    isFamilyFriendly: true,
    isWheelchairAccessible: true,
    hasHalalFood: true,
    avgBudget: 5000,
    waitingTime: 0,
    seatsAvailable: 0,
    openingHours: { mon: "10:00-21:00", tue: "10:00-21:00", wed: "10:00-21:00", thu: "10:00-21:00", fri: "10:00-22:00", sat: "10:00-22:00", sun: "10:00-21:00" },
  },
  // Fast Food
  {
    name: "Burger Palace",
    slug: "burger-palace",
    categoryId: 12,
    description: "Gourmet burgers, crispy fries, and shakes. Fast service with premium quality ingredients.",
    address: "12 Uttara Sector 4, Dhaka 1230",
    latitude: 23.8679,
    longitude: 90.3905,
    phone: "+880-1888990011",
    priceRange: 1,
    rating: 4.2,
    reviewCount: 456,
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800",
    tags: ["Burgers", "Fast Food", "Shakes", "Quick", "Halal"],
    features: ["Quick Service", "Delivery", "Takeaway", "Air Conditioned"],
    isOpen: true,
    isPremium: false,
    isVerified: true,
    hasDelivery: true,
    hasWifi: true,
    hasParking: false,
    isAirConditioned: true,
    isFamilyFriendly: true,
    isWheelchairAccessible: false,
    hasHalalFood: true,
    avgBudget: 450,
    waitingTime: 8,
    seatsAvailable: 35,
    openingHours: { mon: "10:00-23:00", tue: "10:00-23:00", wed: "10:00-23:00", thu: "10:00-23:00", fri: "10:00-00:00", sat: "10:00-00:00", sun: "11:00-22:00" },
  },
  // Beauty Salon
  {
    name: "Glamour Studio",
    slug: "glamour-studio",
    categoryId: 10,
    description: "Premium beauty salon offering haircuts, facials, manicures, and bridal packages. Trained professionals.",
    address: "45 Banani 11, Dhaka 1213",
    latitude: 23.7896,
    longitude: 90.4023,
    phone: "+880-1999001122",
    priceRange: 3,
    rating: 4.6,
    reviewCount: 178,
    imageUrl: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800",
    tags: ["Salon", "Beauty", "Hair", "Spa", "Bridal"],
    features: ["Air Conditioned", "Appointment", "Bridal Package", "Parking"],
    isOpen: true,
    isPremium: true,
    isVerified: true,
    hasDelivery: false,
    hasWifi: true,
    hasParking: true,
    isAirConditioned: true,
    isFamilyFriendly: false,
    isWheelchairAccessible: true,
    hasHalalFood: false,
    avgBudget: 2500,
    waitingTime: 20,
    seatsAvailable: 5,
    openingHours: { mon: "09:00-20:00", tue: "09:00-20:00", wed: "09:00-20:00", thu: "09:00-20:00", fri: "09:00-21:00", sat: "09:00-21:00", sun: "Closed" },
  },
  // Gym
  {
    name: "PowerFit Gym",
    slug: "powerfit-gym",
    categoryId: 11,
    description: "State-of-the-art fitness center with modern equipment, personal trainers, and group classes.",
    address: "67 Mohammadpur, Dhaka 1207",
    latitude: 23.7596,
    longitude: 90.3589,
    phone: "+880-1666778899",
    priceRange: 2,
    rating: 4.4,
    reviewCount: 134,
    imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800",
    tags: ["Fitness", "Gym", "Personal Training", "Classes", "Cardio"],
    features: ["Air Conditioned", "Locker Room", "Personal Trainer", "Group Classes", "Parking"],
    isOpen: true,
    isPremium: false,
    isVerified: true,
    hasDelivery: false,
    hasWifi: true,
    hasParking: true,
    isAirConditioned: true,
    isFamilyFriendly: false,
    isWheelchairAccessible: true,
    hasHalalFood: false,
    avgBudget: 3000,
    waitingTime: 0,
    seatsAvailable: 0,
    openingHours: { mon: "06:00-22:00", tue: "06:00-22:00", wed: "06:00-22:00", thu: "06:00-22:00", fri: "06:00-22:00", sat: "07:00-20:00", sun: "07:00-18:00" },
  },
];

const reviewData = [
  { businessId: 1, userName: "Rahim Ahmed", rating: 5, comment: "Best biryani in Dhaka! The family atmosphere is wonderful and the service is outstanding." },
  { businessId: 1, userName: "Fatima Khan", rating: 4.5, comment: "Excellent food quality. The hilsa preparation is authentic. Slightly pricey but worth it." },
  { businessId: 1, userName: "Mohammad Hasan", rating: 5, comment: "Perfect for family dinners. The ambiance is incredible and staff is very courteous." },
  { businessId: 2, userName: "Nusrat Jahan", rating: 4.5, comment: "Great value for money! The Mughlai dishes are authentic and portion sizes are generous." },
  { businessId: 2, userName: "Kamal Uddin", rating: 4, comment: "Good food, reasonable prices. The butter chicken is a must-try." },
  { businessId: 3, userName: "Tasnia Rahman", rating: 5, comment: "Authentic Japanese experience! The sushi is incredibly fresh. Best in the city." },
  { businessId: 4, userName: "Arif Hossain", rating: 4, comment: "Amazing street food vibes! The fuchka is the best I've ever had." },
  { businessId: 5, userName: "Sara Begum", rating: 5, comment: "Perfect study spot. Great coffee, fast WiFi, and peaceful environment." },
  { businessId: 7, userName: "Rashed Ali", rating: 4.5, comment: "Reliable pharmacy. Always open when I need medicine urgently. Staff is knowledgeable." },
  { businessId: 9, userName: "Dr. Shahid", rating: 4.5, comment: "Excellent medical facilities. The emergency department is well-equipped and responsive." },
];

export async function seed() {
  console.log("🌱 Seeding database...");

  // Insert categories
  for (const cat of categoryData) {
    await db.insert(categories).values(cat);
  }
  console.log("✅ Categories seeded");

  // Insert businesses
  for (const biz of businessData) {
    await db.insert(businesses).values(biz);
  }
  console.log("✅ Businesses seeded");

  // Insert reviews
  for (const rev of reviewData) {
    await db.insert(reviews).values(rev);
  }
  console.log("✅ Reviews seeded");

  console.log("🎉 Database seeded successfully!");
}
